# Generated by Django 5.2.5 on 2025-08-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='type',
            field=models.CharField(choices=[('expense', 'Dépense'), ('income', 'Revenu')], default='expense', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('expense', 'Dépense'), ('income', 'Revenu')], default='expense', max_length=20),
        ),
    ]
